config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'password_resets/create'
  get 'password_resets/update'
  root 'static_pages#home'

  get 'static_pages/home'
  get 'static_pages/help'
  resources :static_pages, only: %i[home help]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :account_activations, only: :edit
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", static_pages_home_path %></li>
        <li><%= link_to "Help", static_pages_help_path %></li>

        <li>
          <%= link_to "English", locale:"en" %>
        </li>
        <li>
          <%= link_to "Vietnamese", locale:"vi" %>
        </li>
        <% if logged_in? %>
          <li><%= link_to t("header.users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown"} do %>
              <%= t "header.account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("header.profile"), current_user %></li>
              <li><%= link_to t("header.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("header.logout"), logout_path, data: { turbo_method: :delete } %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t("header.login"), login_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTutorial</title>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <%= render "layouts/header"%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>